spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password:
  #    driverClassName: org.h2.Driver

  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

